export const languages = [
  { value: 'C', language: 'C' },
  { value: 'C++14', language: 'CPP14' },
  { value: 'C++17', language: 'CPP17' },
  { value: 'Clojure', language: 'CLOJURE' },
  { value: 'C#', language: 'CSHARP' },
  { value: 'Go', language: 'GO' },
  { value: 'Haskell', language: 'HASKELL' },
  { value: 'Java 8', language: 'JAVA8' },
  { value: 'Java 14', language: 'JAVA14' },
  { value: 'JavaScript(Nodejs)', language: 'JAVASCRIPT_NODE' },
  { value: 'Kotlin', language: 'KOTLIN' },
  { value: 'Pascal', language: 'PASCAL' },
  { value: 'Perl', language: 'PERL' },
  { value: 'Python 2', language: 'PYTHON' },
  { value: 'Python 3', language: 'PYTHON3' },
  { value: 'Python 3.8', language: 'PYTHON3_8' },
  { value: 'R', language: 'R' },
  { value: 'Ruby', language: 'RUBY' },
  { value: 'Rust', language: 'RUST' },
  { value: 'Scala', language: 'SCALA' },
  { value: 'Swift', language: 'SWIFT' },
  { value: 'TypeScript', language: 'TYPESCRIPT' },
];
