export const languageExtensions = {
  C: 'c',
  CPP14: 'cpp',
  CPP17: 'cpp',
  CLOJURE: 'clj',
  CSHARP: 'cs',
  GO: 'go',
  HASKELL: 'hs',
  JAVA8: 'java',
  JAVA14: 'java',
  JAVASCRIPT_NODE: 'js',
  KOTLIN: 'kt',
  PASCAL: 'pas',
  PERL: 'pl',
  PYTHON: 'py',
  PYTHON3: 'py',
  PYTHON3_8: 'py',
  R: 'r',
  RUBY: 'rb',
  RUST: 'rs',
  SCALA: 'scala',
  SWIFT: 'swift',
  TYPESCRIPT: 'ts',
};
