export const modeMappings = {
  C: 'text/x-csrc',
  CPP14: 'text/x-c++src',
  CPP17: 'text/x-c++src',
  CLOJURE: 'clojure',
  CSHARP: 'text/x-csharp',
  GO: 'go',
  HASKELL: 'haskell',
  JAVA8: 'text/x-java',
  JAVA14: 'text/x-java',
  JAVASCRIPT_NODE: 'javascript',
  KOTLIN: 'text/x-kotlin',
  PASCAL: 'pascal',
  PERL: 'perl',
  PYTHON: 'python',
  PYTHON3: 'python',
  PYTHON3_8: 'python',
  R: 'r',
  RUBY: 'ruby',
  RUST: 'rust',
  SCALA: 'text/x-scala',
  SWIFT: 'swift',
  TYPESCRIPT: 'javascript',
};
